sudo: required

language: generic

services:
  - docker

install:
  - cp config/database.yml.test.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose -f docker-compose.test.yml up -d --build
  - >
    while ! docker logs mapknitter-test | grep "Phusion Passenger Standalone web server started"; do
      echo "Waiting for start script to finish...";
      sleep 20;
    done; echo "Done!"
  - docker-compose -f docker-compose.test.yml exec web bash -lc "rake db:setup || rake db:migrate"

env:
  global:
    - RAILS_ENV=test
  matrix:
    - TASK="docker-compose -f docker-compose.test.yml exec web bash -lc 'CI=true TRAVIS=true rake test:unit'"
    - TASK="docker-compose -f docker-compose.test.yml exec web bash -lc 'CI=true TRAVIS=true rake test:integration'"
    - TASK="docker-compose -f docker-compose.test.yml exec web bash -lc 'CI=true TRAVIS=true rake test:functional'"
    - TASK="docker-compose -f docker-compose.test.yml exec web bash -lc 'CI=true TRAVIS=true RAILS_ENV=production rake assets:precompile'"

script:
  - $TASK
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - main
    - unstable
    - issue958-travis-workflow-continued

