language: ruby
rvm:
  - 2.4.6

services:
  - mysql

install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - bundle install
  - bundle exec rake db:setup || bundle exec rake db:migrate

env:
  global:
    - RAILS_ENV=test
    - CI=true
    - TRAVIS=true
  matrix:
    - TASK="rake test:unit"
    - TASK="rake test:integration"
    - TASK="rake test:functional"

script:
  - bundle exec $TASK
  - >    
    bundle exec rake test > /dev/null 2>&1 &&
    bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - main
    - unstable

