version: '3.3'
services:
  db:
    image: mysql:5.7

  web:
    container_name: mapknitter-test
    build: .
    network_mode: host
    env_file:
      - mapknitter.test.env
    volumes:
      - .:/app
